package com.dnoel.markeralerts.tools

import java.nio.file.Files
import java.nio.file.Path
import java.sql.Connection
import java.sql.DriverManager

/**
 * Writes the prebuilt SQLite file that ships inside the APK.
 *
 * The schema is written by hand here rather than generated by Room, because
 * :tools is a plain JVM module with no Android on the classpath. It must match
 * what Room expects in M2 exactly — column names, types, and the index — or
 * Room will reject the prepackaged database at open time.
 */
class DatabaseWriter(private val output: Path) {

    fun write(markers: List<EnrichedMarker>, roomIdentityHash: String?) {
        Files.deleteIfExists(output)
        output.parent?.let { Files.createDirectories(it) }

        DriverManager.getConnection("jdbc:sqlite:${output.toAbsolutePath()}").use { conn ->
            conn.autoCommit = false
            createSchema(conn)
            insertAll(conn, markers)
            roomIdentityHash?.let { stampRoomIdentity(conn, it) }
            conn.commit()

            // Reclaim the space freed by the bulk insert's page churn; this is
            // a read-only asset so the file should be as small as possible.
            conn.autoCommit = true
            conn.createStatement().use { it.execute("VACUUM") }
        }
    }

    private fun createSchema(conn: Connection) {
        conn.createStatement().use { st ->
            st.execute(
                """
                CREATE TABLE IF NOT EXISTS markers (
                    -- The location GUID, unique per physical point. NOT the
                    -- reference number: one National Register listing can cover
                    -- many contributing buildings, and refnum identifies the
                    -- listing while geomId identifies the place. Using a GUID
                    -- from the source rather than a row number keeps ids stable
                    -- when the data is regenerated, which matters once M3 starts
                    -- recording which markers have already been passed.
                    geomId TEXT NOT NULL PRIMARY KEY,
                    refnum TEXT NOT NULL,
                    name TEXT NOT NULL,
                    resType TEXT,
                    address TEXT,
                    city TEXT,
                    county TEXT,
                    state TEXT NOT NULL,
                    certDate TEXT,
                    lat REAL NOT NULL,
                    lon REAL NOT NULL,
                    alertable INTEGER NOT NULL,
                    wikiTitle TEXT,
                    wikiUrl TEXT,
                    blurb TEXT
                )
                """.trimIndent(),
            )
            // The proximity query filters on a lat/lon bounding box before it
            // refines with Haversine, so this composite index is the thing that
            // makes the whole approach viable — and it is what has to carry the
            // national 72,668-row set later without a redesign.
            st.execute("CREATE INDEX IF NOT EXISTS index_markers_lat_lon ON markers (lat, lon)")
            // Non-unique by design: this is how the contributing buildings of
            // one historic district are found together.
            st.execute("CREATE INDEX IF NOT EXISTS index_markers_refnum ON markers (refnum)")
        }
    }

    private fun insertAll(conn: Connection, markers: List<EnrichedMarker>) {
        val sql = """
            INSERT INTO markers
                (geomId, refnum, name, resType, address, city, county, state, certDate,
                 lat, lon, alertable, wikiTitle, wikiUrl, blurb)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """.trimIndent()

        conn.prepareStatement(sql).use { ps ->
            for (enriched in markers) {
                val m = enriched.marker
                ps.setString(1, m.geomId)
                ps.setString(2, m.refnum)
                ps.setString(3, m.name)
                ps.setString(4, m.resType)
                ps.setString(5, m.address)
                ps.setString(6, m.city)
                ps.setString(7, m.county)
                ps.setString(8, m.state)
                ps.setString(9, m.certDate)
                ps.setDouble(10, m.lat)
                ps.setDouble(11, m.lon)
                ps.setInt(12, if (enriched.alertable) 1 else 0)
                ps.setString(13, enriched.wiki?.title)
                ps.setString(14, enriched.wiki?.url)
                ps.setString(15, enriched.wiki?.blurb)
                ps.addBatch()
            }
            ps.executeBatch()
        }
    }

    /**
     * Room refuses to open a prepackaged database unless `room_master_table`
     * holds the identity hash of the schema it was compiled against, failing
     * with "Pre-packaged database has an invalid schema".
     *
     * The hash is not knowable until the @Database class exists and Room has
     * exported its schema JSON, which happens in M2. Until then this is skipped
     * and the file is a plain SQLite database — perfectly readable, just not
     * yet openable by Room.
     */
    private fun stampRoomIdentity(conn: Connection, identityHash: String) {
        conn.createStatement().use { st ->
            st.execute(
                "CREATE TABLE IF NOT EXISTS room_master_table " +
                    "(id INTEGER PRIMARY KEY, identity_hash TEXT)",
            )
            st.execute("DELETE FROM room_master_table")
        }
        conn.prepareStatement(
            "INSERT INTO room_master_table (id, identity_hash) VALUES (42, ?)",
        ).use { ps ->
            ps.setString(1, identityHash)
            ps.executeUpdate()
        }
    }
}
