package com.dnoel.markeralerts.data

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

/**
 * Opens the prebuilt marker database shipped in assets.
 *
 * Nothing is ever written to this database at runtime — it is a read-only
 * reference dataset regenerated by `:tools` and replaced wholesale on release.
 * That is why there are no migrations here: a schema change means regenerating
 * the asset, not migrating a user's copy.
 */
@Database(entities = [MarkerEntity::class], version = 1, exportSchema = true)
abstract class MarkerDatabase : RoomDatabase() {

    abstract fun markerDao(): MarkerDao

    companion object {
        private const val ASSET = "markers.db"

        fun build(context: Context): MarkerDatabase =
            Room.databaseBuilder(context, MarkerDatabase::class.java, "markers.db")
                // Room will reject this asset unless its room_master_table
                // holds the identity hash of the schema compiled above. The
                // hash lives in app/schemas/…/1.json and is fed to :tools,
                // which stamps it into the file.
                .createFromAsset(ASSET)
                .build()
    }
}
